### ISSUE TITLE
Implement Screen Shake

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#21]

**Comment by henriiquecampos** [comment]
Ohh this is already on the bake, you can pretty much be sure that it will be a feature in the next release!

![screen_shake](https://user-images.githubusercontent.com/10171059/43837532-338a2a3a-9aef-11e8-81f0-37237b9392bf.gif)

**Comment by henriiquecampos** [comment]
Done at #34 give it a try :smile:
