### ISSUE TITLE
Ability to Jump down non-solid platform using Down+Jump

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#23]
This feature is inspired from Momodora and Dead Cells.

Of course this should only be for non-solid platforms.

**Comment by henriiquecampos** [comment]
Ohh yeah! This is totally mandatory, for sure! I think that this will be implemented together with #18 since both will use the same approach, while this one makes the character fall, #18 will make it climb down.

Thanks for the reminder!
