### ISSUE TITLE
Solid Platforms that stop the player and don't allow the player to jump up through them

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#24]
The are necessary for some games.

So, there should be platforms that allow the player to jump up through them and ones that stops the up movement player once the player touches them

**Comment by henriiquecampos** [comment]
Ohh, you mean a normal "not-pass" static platform? They are already available, both the pass-through and the "solid ones". There's even a template tileset scene for them.

![image](https://user-images.githubusercontent.com/10171059/43923888-76e975fa-9bf9-11e8-94a7-427b30c716d2.png)

It is the [tileset template scene](https://github.com/pigdevstudio/platform_template/blob/master/source/areas/tileset_template.tscn) in the template :D
