### ISSUE TITLE
Player able to jump in air for some time after wall jump

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#25]
This is happening in the platformer template.
You are able to jump in air for some reason.
Once you wall jump.
And keep pressing in that direction.
The state that checks if wall jumping is stuck or something.
![image](https://imgur.com/download/T9F9KLM)

**Comment by Logmytech** [comment]
@henriiquecampos Kinda fixed the problem
```
func input_process(actor, event):
    if event.is_action_pressed(actor.jump):
        if Input.is_action_pressed(actor.dash):
            actor.velocity.x = (wall_jump * normal.x)
            actor.velocity.y = -wall_jump * dash_jump_multiplier
            actor.emit_signal("perform_action", "jump")
        elif actor.is_on_wall():
                actor.velocity.x = wall_jump * normal.x
                actor.velocity.y = -wall_jump
                actor.emit_signal("perform_action", "jump")
```

**Comment by henriiquecampos** [comment]
Awesome! Thanks for the help :blue_heart: so this is fixed now, right? I'm closing this issue then! :tada:
