### ISSUE TITLE
Add a Coyote Timer and Jump Input buffering

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#36]
https://www.gamasutra.com/blogs/LisaBrown/20171005/307063/GameMaker_Platformer_Jumping_Tips.php
https://www.youtube.com/watch?v=vFsJIrm2btU

Most modern platformers have a Coyote timer.
Meaning Character can still jump for some time after they have gotten off the floor.

Also there is jump input buffering needed for polish. If player presses jump just before landing it will not register and player will feel they pressed jump and didn't jump. They will feel the game is buggy.

Here are demo images.

##### Without Coyote timer
![Jump Without Coyote timer](https://www.gamasutra.com/db_area/images/blog/307063/ledgeassist.gif)

##### With Coyote timer
![Jump with Coyote timer](https://www.gamasutra.com/db_area/images/blog/307063/ledgeassist2.gif)

##### Without Jump input buffering
![Jump Without input buffering](https://www.gamasutra.com/db_area/images/blog/307063/jumpbuffer.gif)

##### With Jump input buffering
![Jump With input buffering](https://www.gamasutra.com/db_area/images/blog/307063/jumpbuffer2.gif)

**Comment by henriiquecampos** [comment]
Let's break this into two issues: 
- Coyote Fall-Timer
- Jump buffering

The Coyote fall-timer is a really improvement to the game feeling I'll actually add it into [milestones/juiceness](https://github.com/pigdevstudio/platform_template/milestone/5).

But the jump buffering is different, it seems that I'll need some work-around (maybe a raycast or something) to actually achieve it and I don't see this in many games, although it seems a good thing to have, I'll postpone it for a future update. Although I'll be really happy if someone is able to implement it and make a **PR** :stuck_out_tongue:

**Comment by henriiquecampos** [comment]
Awesome, I implemented it at 36023ce check it out! Closing the issue until further feedback :pig:

**Comment by Logmytech** [comment]
I think you'd just need to check if Player is falling and set a timer and if the player hits the wall below during the timer, you jump.

I don't think a raycast is needed.
