### ISSUE TITLE
Unable to climb up ladder after climbing down the ladder passing through a platform in development branch

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#41]
![Unable to climb up ladder](https://i.imgur.com/FhUVPTX.gif)

**Comment by henriiquecampos** [comment]
I think this is fixed on https://github.com/pigdevstudio/platform_template/commit/910b0e7e0fe818062f4b41c41bac8700498df87c since the ladders approach changed, check it out there, I'll close this for now, you can reopen if you realize this is still there
