### ISSUE TITLE
Ladder: Character jerkily teleports towards  the center of the ladder in Dev branch

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#42]
![Teleport to ladder](https://i.imgur.com/ZqojY5f.gif)

I think there is no need to teleport the player to the center.
We could instead allow the player to be in climb state as long as one is colliding.
Daisy Dangerous allows the player to climb the ladder as long as one is colliding withe the ladder and the game doesn't need the player centered in the ladder.

Or if you do want to be at the center you could slowly move the player in that direction.

**Comment by henriiquecampos** [comment]
Ok, so for this one I think that a simple "snap" `bool` on the ladder will do the trick.

if snap is turned on, the character snaps to the ladder's center, otherwise it just starts climbing wherever it grabbed on the ladder, wachu think @Logmytech ?

**Comment by Logmytech** [comment]
In case you do snap wouldn't it be cool to move very fastly to the center.

That would remove the jerky teleport.

**Comment by henriiquecampos** [comment]
I think this is fixed on https://github.com/pigdevstudio/platform_template/commit/910b0e7e0fe818062f4b41c41bac8700498df87c I won't add a smoothing when the `snap` config is turned on...snapping teleports to the snapping point, so not smoothing when snap is on. :laughing:
