### ISSUE TITLE
Ladder: Player able to move into platform when climbing down in dev branch

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#43]
![Move through platform](https://i.imgur.com/fBjnXM7.gif)

**Comment by henriiquecampos** [comment]
This is also fixed on https://github.com/pigdevstudio/platform_template/commit/910b0e7e0fe818062f4b41c41bac8700498df87c whenever the character `is_on_floor` it will switch to the `idle` state, so I'm closing it now, feel free to reopne if you find out that this is still happening.
