### ISSUE TITLE
Jump down platform: Platforms should be thin in dev branch

### ISSUE THREAD

**Issue by Logmytech** [pigdevstudio/platform_template#44]
Generally in most platformer games which have jump down and pass through platforms, the platforms are thin. A lot thinner than the solid platforms.

Even in Daisy Dangerous, Momodora and Dead Cells the jump through platforms are thin.

But in the dev branch the pass through platforms are pretty thick, even thicker than the solid ones.

**Comment by henriiquecampos** [comment]
Hmm, isn't that just...a design issue? I mean, each user will probably draw their own shapes (probably to match their art as well) :thinking: 

Also, the template level currently is just a big playground to test use cases, by no means it is (currently) meant to be a starting point to level design. I should probably rename it (or even remove it from the repo to avoid misuses).

But yeah I think this is more related to the final design than to the template itself. As long as the template offers the platforms to be instantiated and edited within the editor and customizable, I think it will be OK. So...I think I'll close this as is more related to each user preference than to the template by itself.
